spring:
  application:
    name: mybatis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.6.132:3306/sell?useSSL=false&characterEncoding=utf-8

server:
  port: 8888
  servlet:
    context-path: /mybatis
logging:
  level:
    com.sml.mybatis.mapper: debug
  pattern:
    console: "%d - %msg"



